### TRANSACTION MAP ###
transaction_map = {
    "ASSIGN (BEG)": "Beginning Cap Acct Bal",
    "BAL FWD": "Beginning Cap Acct Bal",
    "CE AD COST": "Expense",
    "CE ADMIN": "Expense",
    "CE AUDIT": "Expense",
    "CE CUST FE": "Expense",
    "CE FCE": "Expense",
    "CE HED FEE": "Expense",
    "CE IF": "Mgmt Fee Waiver",
    "CE IIEA": "Income",
    "CE IIEM": "Income",
    "CE IIF": "Income",
    "CE IIM": "Income",
    "CE IIMM": "Income",
    "CE IIR": "Income",
    "CE MF": "Mgmt Fee",
    "CE MFW": "Mgmt Fee Waiver",
    "CE MREAL": "Mark to Market",
    "CE MUNREAL": "Mark to Market",
    "CE ORG EXP": "Expense",
    "CE OTH FEE": "Expense",
    "CE RADJEXP": "Expense",
    "CE RADJINC": "Income",
    "CONT": "Contribution",
    "Total": "Ending Cap Acct Bal",
    "WITH (BEG)": "Withdrawal - BOP",
    "WITH (END)": "Withdrawal - EOP",
}
